title: Sid's Personal Website
author: Siddharth Srinivasan
email: sidgs09@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website which displays my accomplishments and hobbies. Please follow my social media accounts and DM me to get in touch!

# social links
instagram_username: sid.srinivasan
github_username:  sidgs09

show_excerpts: true # set to false to remove excerpts on the homepage
